mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/lingh/mapper/*.xml
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: false
        web-admin-password: 123456
  shardingsphere:
    mode:
      type: Memory
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:ds0;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql'
        username: sa
        password: ""
    rules:
      sharding:
        tables:
          t_order:
            actual-data-nodes: ds0.t_order_202202$->{16..20}
            tableStrategy:
              standard:
                sharding-column: datadate
                sharding-algorithm-name: lingh-interval
        sharding-algorithms:
          lingh-interval:
            type: INTERVAL
            props:
              datetime-pattern: "yyyy-MM-dd HH:mm:ss.SSS"
              datetime-lower: 2022-02-16 00:00:00.000
              datetime-upper: 2022-02-20 23:59:59.999
              sharding-suffix-pattern: _yyyyMMdd
              datetime-interval-amount: 1
              datetime-interval-unit: DAYS